### ISSUE TITLE
Sponsor- and Sometimes Ad-Blocking No Longer Work

### ISSUE THREAD

**Issue by halotroop2288** [BowDown097/QtTube#13]
Both ad blocking and SponsorBlock are enabled, but lately SponsorBlock does not work at all. And sometimes even ads play inside QtTube. Which I wouldn't think could actually be a problem in a custom client like this, since ads usually have to be implemented manually. 🤨

P.S. the menu bar auto-hiding is really annoying, please let me disable that. kthxbai <3

P.P.S. I might just close this because despite updating via `yay -Syu` nearly every day, QtTube apparently hasn't been updated since August 7th, and now I have a newer build, in which SponsorBlock at least seems to be working so far.

**Comment by halotroop2288** [comment]
OK. Tested on 95e1f42, built on September 16, 2024. SponsorBlock is definitely inconsistent if it works at all.

**Comment by BowDown097** [comment]
That's really odd if that's the case. SponsorBlock WAS broken thanks to the latest Qt update, but it should have been fixed in the commit 30b3903, from about a month ago. Are there any errors logged if you run the program in the terminal?

And yeah, I've had pre-roll ads show up super rarely a few times too. I think the patch for them is just not getting injected fast enough sometimes, especially if you have a fast connection. I looked into it when I first had it happen but couldn't figure anything out. Worth a try again though.

> P.S. the menu bar auto-hiding is really annoying, please let me disable that. kthxbai <3

Oh, I was going to do this, but I forgot since it never really bugged me. Should be easy.

**Comment by BowDown097** [comment]
There's an "auto-hide top bar" setting now.

**Comment by halotroop2288** [comment]
> There's an "auto-hide top bar" setting now.

@BowDown097 I tried updating it from yay and GCC ran into a segfault (reproducible)

[gcc-segfault.log](https://github.com/user-attachments/files/17022395/gcc-segfault.log)

**Comment by BowDown097** [comment]
Well the error seems to originate from a Qt header that's included in one of the files, and I haven't changed any of the files in the stacktrace in ages, so it's definitely not anything to do with the program.

**Comment by halotroop2288** [comment]
I fixed it by running a cleanBuild. There is an issue with the drop-down setting though. It causes the menu bar to be permanently hidden until the app is hidden.

**Comment by BowDown097** [comment]
Good catch. Fixed it.

**Comment by BowDown097** [comment]
Okay, the ad blocking injects a little faster now.

> I think the patch for them is just not getting injected fast enough sometimes, especially if you have a fast connection.

We'll see if this theory is correct. I haven't gotten anything yet.

**Comment by BowDown097** [comment]
Haven't gotten ads a single time after all this time of regular use, I think it's fixed.
