### ISSUE TITLE
External player usage

### ISSUE THREAD

**Issue by dvd73** [BowDown097/QtTube#15]
Hi

Is it possible to use an external player like mpv or smplayer?
These players are support hardware acceleration and I'm using its for all h264/mp4 content. Now I'm able to watch youtube videos by url in SMPlayer/mpv but I'm missing a way to observe all my subscription videos. I consider using QtPlayer for this.

Thanks.

**Comment by BowDown097** [comment]
This was previously a feature in the program in the very beginning, but I removed it because I didn't know how to make it work with the watch view (the part with the title, description, recommendations, etc.). That eventually transformed into building MPV into the watch view as an option, but the implementation really sucked, so I also removed that.

If you don't care about the watch view, then I could add the external player option back. Should be a simple enough change. I just figured the watch view's kind of a core part of the program and not having it would be weird.

**Comment by dvd73** [comment]
Yes, it would be great to have such an opportunity as to launch an external player: just specify somewhere in the QtTube settings the path to the external player. Example:

- textbox for path to the external player: 
- sample value I could setup later:  /usr/bin/mpv [parameters] %U 

where %U - placeholder for video URL you pass into

Thanks a lot )

**Comment by BowDown097** [comment]
I added it as a setting.
