### ISSUE TITLE
Style settings in KDE not honoured

### ISSUE THREAD

**Issue by zynexiz** [BowDown097/QtTube#6]
Just found this app and tried it on Arch with KDE. Seems to work nice (except login didn't work at first). But it seems to be hard coded to use Fusion application style? I use Kvantum, but also tried other styles (like Breeze) without it changing anything. The tabs and colours still looks like it uses Fusion. It should respect the colour and style set by the OS to look more consistent.

Some future features that would be nice is the possibility to have a card style layout (like FreeTube) and the possibility to import subscriptions from other apps like NewPipe so you don't need to login to YouTube at all.

Otherwise it's a nice addition to apps like FreeTube to get a more integrated app for KDE :)

**Comment by BowDown097** [comment]
I HATE hard-coded styles so I would never do that, lol. Does theming work fine with another DE/WM/whatever? Does the program log anything out of place related to theming in the terminal? I'm using Openbox and all Qt themes work just fine.

Also, I want to do the layout you speak of as well but I had a really hard time doing it (it's what I was shooting for when I first made the program) and just ended up using list views. I'll probably get to it eventually because it would look better.

Also also subscription imports/exports are on the roadmap but it's the last thing I'm going to do on it so it will probably take a while assuming no one comes by and adds it themselves.

**Comment by BowDown097** [comment]
Should be fixed with the Application Style option in the settings menu I added a while ago.
